### ISSUE TITLE
Property 'orderBy' does not exist on type 'LoDashStatic'.

### ISSUE THREAD

**Issue by yahyaKacem** [TheLarkInn/ngconf-webpack-wall-of-awesome#1]
Hi, I cloned your repo and run `npm i` went OK, then `typings i`got this error:

```
typings ERR! message Attempted to compile "zone.js" as an external module, but it looks like a global module.

typings ERR! cwd /path/to/repos/ngconf-webpack-wall-of-awesome
typings ERR! system Linux 3.16.0-71-generic
typings ERR! command "~/.nvm/versions/node/v6.1.0/bin/node" "~/.nvm/versions/node/v6.1.0/bin/typings" "i"
typings ERR! node -v v6.1.0
typings ERR! typings -v 1.0.4

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

but the typings folder was created so I run the `npm run server:dev` and I get this errors:

```
[default] /path/to/repos/ngconf-webpack-wall-of-awesome/src/app/utils.ts:4:11 
    Property 'orderBy' does not exist on type 'LoDashStatic'.
[default] /path/to/repos/ngconf-webpack-wall-of-awesome/typings/browser/ambient/lodash/index.d.ts:15827:5 
    Duplicate identifier 'export='.
[default] /path/to/repos/ngconf-webpack-wall-of-awesome/typings/browser/definitions/lodash/index.d.ts:18292:1 
    Duplicate identifier 'export='.

```

**Note:** I'm using:
tried Node: 6.1.0 and 6.2.0 
NPM: 3.9.1 and 3.8.9 and 3.9.3
typings: 1.0.4

**Comment by TheLarkInn** [comment]
I can push a quick fix for this. Test it on your side by removing loash from "ambient" and then deleting your Typings folder and running `typings i` again.

**Comment by TheLarkInn** [comment]
Should be fixed by b0b4ce2466e012c9f4cacfaff6d72ed31926064c

**Comment by yahyaKacem** [comment]
Thanks, that did work, but after `typings i` you need to run `npm i` for some reason some of the typings only gets installed after you run `npm i`.

**Comment by anrepppp** [comment]
Property 'sortByOrder' does not exist on type 'LoDashStatic' what is the solution for this.
